### ISSUE TITLE
1.12.2 version has duplicate id to "Into the Jungle" mod.

### ISSUE THREAD

**Issue by dalekfan** [Fourmisain/IndyPets#10]
![1 12 2 duplicate id](https://user-images.githubusercontent.com/49622705/176986778-809bc11d-763b-45fd-bb2e-4be9e06ccc9b.PNG)
yea

**Comment by Fourmisain** [comment]
Please see https://github.com/Fourmisain/IndyPets/issues/7#issuecomment-1166276391.
