### ISSUE TITLE
Cobblemon incompatibility

### ISSUE THREAD

**Issue by Hunter-495** [Fourmisain/IndyPets#15]
Issue: When using the cobblemon mod, this mod overwrites rightclick behaviors (held items and shoulder mounting).
Possible Solution: blacklist mod interaction with cobblemon entities or add a config to enable on to do so.

**Comment by Fourmisain** [comment]
You can already change or blacklist the right click behavior in the config.

**Comment by Fourmisain** [comment]
Just released new versions with a separate Interact hotkey (H) and a sneak interact blocklist afterall, containing cobblemon by default.

The "sneak interact while holding a specific item" way I mentioned still works too of course (just don't forget to remove cobblemon from the blocklist).
