### ISSUE TITLE
Crash caused by Unwhistling with a Goat Horn with "Use particle effects instead of status messages" enabled

### ISSUE THREAD

**Issue by diegoadobo** [Fourmisain/IndyPets#25]
Consistent serverside crash when trying to spawn particle effects when unwhistling with a goat horn. Version 1.21.4

**Comment by Fourmisain** [comment]
Oh, looks like there was a breaking change in 1.21.4 that I didn't catch.

Really simple fix,1.4.4 is out!

P.S.
Nice to know people are actually using the goat horn feature!
